name: Python Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dev
        run: python dev.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Test
        run: python test.py

  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Prod
        run: python prod.py
